### ISSUE TITLE
Contract for constructor

### ISSUE THREAD

**Issue by mcandre** [sefaira/rho-contracts.js#20]
An easier way to match objects is by constructor. Could we get a contract for matching against arbitrary constructors, e.g. `Date`, `RedisClient`, `Thetan`?

**Comment by gmarceau** [comment]
Isn't that what `c.isA(Date)` does?

**Comment by mcandre** [comment]
I must not have the syntax right, because when I try

```
// Convert a Date to a number of Swatch beats
var beats = c.fun({ d: c.isA(Date) })
      .returns(c.number)
      .wrap(
        function(d) {
          var
          utc = new Date(
            d.getUTCFullYear(),
            d.getUTCMonth(),
            d.getUTCDate(),
            d.getUTCHours(),
            d.getUTCMinutes(),
            d.getUTCSeconds()
          ),
          seconds = utc.getHours() * 3600 + utc.getMinutes() * 60 + utc.getSeconds(),
          bmt = seconds + 3600;

          return (bmt / 86.4) % 1000;
        }
      );
```

Yields

```
/Users/andrew/src/node-swatch/node_modules/rho-contracts/contract.impl.js:336
           fail: function (e) { e.captureStack(); throw e },
                                                        ^
ContractError: on `isA()` Wrong number of arguments, expected 2 but got 1

  at null (/Users/andrew/src/node-swatch/lib/swatch.js:8:26)
  at Module._compile (module.js:456:26)
  at Module._extensions..js (module.js:474:10)
  at Module.load (module.js:356:32)
  at Module._load (module.js:312:12)
  at Module.require (module.js:364:17)
```

**Comment by gmarceau** [comment]
`c.isA()` takes two arguments, the construction and the name of the constructor as a string. Granted it would be better if it could infer the name from the constructor itself.

**Comment by mcandre** [comment]
plain JavaScript can test constructors with `value.constructor === SomeConstructor`.

Example:

```
> (new Date()).constructor === Date
true
```

Could rho-contracts offer a check closer to this interface?

**Comment by gmarceau** [comment]
This too sounds like a contract that belong in a project-local custom contract file.
`cc.isExactly = function (constructor) { return c.and(c.object({}), c.pred(function (v) { return v.constructor == constructor; }))}`

**Comment by mcandre** [comment]
> c.isA() takes two arguments, the construction and the name of the constructor as a string. Granted it would be better if it could infer the name from the constructor itself.

ECMAScript offers `object.constructor === SomeConstructor`. In the future, could rho-contracts simply leverage this, to make the `isA()` API simpler?

**Comment by gmarceau** [comment]
The `isA` issues is now fixed on the @bodylabs fork https://github.com/bodylabs/rho-contracts.js
