### ISSUE TITLE
Error with c.object contract on Set, Map return types

### ISSUE THREAD

**Issue by mcandre** [sefaira/rho-contracts.js#21]
I can write contracts for most of my pangram library's functions, but when I try to contract the return type as a `c.object` for a Set or Map, I get a weird rho-contracts error.

# Trace

```
$ git clone git@github.com:mcandre/pangrams.git
$ cd pangrams/
(master)$ npm test

> pangrams@0.0.1 test /Users/andrew.pennebaker/src/pangrams
> mocha



  pangrams
    pangrams
[0G      ✓ contents are all, in fact, pangrams 
    isPangram
[0G      ✓ should handle false positives 
[0G      ✓ should ignore case 
[0G      ✓ should ignore punctuation 
[0G      ✓ should handle unicode 
    isAnagram
[0G      ✓ handle false positivies 
[0G      ✓ handle true positivies 
    lipogram
[0G      ✓ should handle true positives 
    isPangrammaticLipogram
[0G      ✓ should handle true positives 
    isogram
[0G      ✓ should handle true positives 
    isogram
[0G      ✓ should handle true positives 
    heterogram
[0G      ✓ should handle true positives 
[0G      ✓ should handle true negatives 


  13 passing (58ms)

(master) $ git checkout contracts
(contracts) $ npm test

> pangrams@0.0.1 test /Users/andrew.pennebaker/src/pangrams
> mocha



  pangrams
    pangrams
[0G      ✓ contents are all, in fact, pangrams 
    isPangram
[0G      1) should handle false positives
[0G      ✓ should ignore case 
[0G      ✓ should ignore punctuation 
[0G      ✓ should handle unicode 
    isAnagram
[0G      ✓ handle false positivies 
[0G      ✓ handle true positivies 
    lipogram
[0G      2) should handle true positives
    isPangrammaticLipogram
[0G      3) should handle true positives
    isogram
[0G      4) should handle true positives
    isogram
[0G      5) should handle true positives
    heterogram
[0G      6) should handle true positives
[0G      7) should handle true negatives


  6 passing (37ms)
  7 failing

  1) pangrams isPangram should handle false positives:
     ContractError: on `object()`
(contract was wrapped at: /Users/andrew.pennebaker/src/pangrams/node_modules/rho-contracts/index.js:5)
Expected contract, but got undefined
for the key `0` of the hash.
at position .fieldContracts
in contract:
c.fun({ fieldContracts: c.optional(c.hash(c.contract)) } -> c.objectContractObject)

    at null (/Users/andrew.pennebaker/src/pangrams/lib/pangrams.js:66:18)
    at r (/Users/andrew.pennebaker/src/pangrams/node_modules/rho-contracts/contract.impl.js:891:23)
    at null (/Users/andrew.pennebaker/src/pangrams/test/test.js:33:18)
    at callFn (/Users/andrew.pennebaker/src/pangrams/node_modules/mocha/lib/runnable.js:249:21)
    at Runnable.run (/Users/andrew.pennebaker/src/pangrams/node_modules/mocha/lib/runnable.js:242:7)
    at Runner.runTest (/Users/andrew.pennebaker/src/pangrams/node_modules/mocha/lib/runner.js:373:10)
    at null (/Users/andrew.pennebaker/src/pangrams/node_modules/mocha/lib/runner.js:451:12)
    at next (/Users/andrew.pennebaker/src/pangrams/node_modules/mocha/lib/runner.js:298:14)
    at null (/Users/andrew.pennebaker/src/pangrams/node_modules/mocha/lib/runner.js:308:7)
    at next (/Users/andrew.pennebaker/src/pangrams/node_modules/mocha/lib/runner.js:246:23)
    at null (/Users/andrew.pennebaker/src/pangrams/node_modules/mocha/lib/runner.js:275:5)
    at processImmediate (timers.js:363:15)

  2) pangrams lipogram should handle true positives:
     ContractError: on `object()`
(contract was wrapped at: /Users/andrew.pennebaker/src/pangrams/node_modules/rho-contracts/index.js:5)
Expected contract, but got undefined
for the key `0` of the hash.
at position .fieldContracts
in contract:
c.fun({ fieldContracts: c.optional(c.hash(c.contract)) } -> c.objectContractObject)

    at null (/Users/andrew.pennebaker/src/pangrams/test/test.js:114:20)
    at callFn (/Users/andrew.pennebaker/src/pangrams/node_modules/mocha/lib/runnable.js:249:21)
    at Runnable.run (/Users/andrew.pennebaker/src/pangrams/node_modules/mocha/lib/runnable.js:242:7)
    at Runner.runTest (/Users/andrew.pennebaker/src/pangrams/node_modules/mocha/lib/runner.js:373:10)
    at null (/Users/andrew.pennebaker/src/pangrams/node_modules/mocha/lib/runner.js:451:12)
    at next (/Users/andrew.pennebaker/src/pangrams/node_modules/mocha/lib/runner.js:298:14)
    at null (/Users/andrew.pennebaker/src/pangrams/node_modules/mocha/lib/runner.js:308:7)
    at next (/Users/andrew.pennebaker/src/pangrams/node_modules/mocha/lib/runner.js:246:23)
    at null (/Users/andrew.pennebaker/src/pangrams/node_modules/mocha/lib/runner.js:275:5)
    at processImmediate (timers.js:363:15)

  3) pangrams isPangrammaticLipogram should handle true positives:
     ContractError: on `object()`
(contract was wrapped at: /Users/andrew.pennebaker/src/pangrams/node_modules/rho-contracts/index.js:5)
Expected contract, but got undefined
for the key `0` of the hash.
at position .fieldContracts
in contract:
c.fun({ fieldContracts: c.optional(c.hash(c.contract)) } -> c.objectContractObject)

    at null (/Users/andrew.pennebaker/src/pangrams/lib/pangrams.js:76:18)
    at r (/Users/andrew.pennebaker/src/pangrams/node_modules/rho-contracts/contract.impl.js:891:23)
    at null (/Users/andrew.pennebaker/src/pangrams/test/test.js:137:18)
    at callFn (/Users/andrew.pennebaker/src/pangrams/node_modules/mocha/lib/runnable.js:249:21)
    at Runnable.run (/Users/andrew.pennebaker/src/pangrams/node_modules/mocha/lib/runnable.js:242:7)
    at Runner.runTest (/Users/andrew.pennebaker/src/pangrams/node_modules/mocha/lib/runner.js:373:10)
    at null (/Users/andrew.pennebaker/src/pangrams/node_modules/mocha/lib/runner.js:451:12)
    at next (/Users/andrew.pennebaker/src/pangrams/node_modules/mocha/lib/runner.js:298:14)
    at null (/Users/andrew.pennebaker/src/pangrams/node_modules/mocha/lib/runner.js:308:7)
    at next (/Users/andrew.pennebaker/src/pangrams/node_modules/mocha/lib/runner.js:246:23)
    at null (/Users/andrew.pennebaker/src/pangrams/node_modules/mocha/lib/runner.js:275:5)
    at processImmediate (timers.js:363:15)

  4) pangrams isogram should handle true positives:
     ContractError: on `object()`
(contract was wrapped at: /Users/andrew.pennebaker/src/pangrams/node_modules/rho-contracts/index.js:5)
Expected contract, but got undefined
for the key `0` of the hash.
at position .fieldContracts
in contract:
c.fun({ fieldContracts: c.optional(c.hash(c.contract)) } -> c.objectContractObject)

    at null (/Users/andrew.pennebaker/src/pangrams/test/test.js:150:20)
    at callFn (/Users/andrew.pennebaker/src/pangrams/node_modules/mocha/lib/runnable.js:249:21)
    at Runnable.run (/Users/andrew.pennebaker/src/pangrams/node_modules/mocha/lib/runnable.js:242:7)
    at Runner.runTest (/Users/andrew.pennebaker/src/pangrams/node_modules/mocha/lib/runner.js:373:10)
    at null (/Users/andrew.pennebaker/src/pangrams/node_modules/mocha/lib/runner.js:451:12)
    at next (/Users/andrew.pennebaker/src/pangrams/node_modules/mocha/lib/runner.js:298:14)
    at null (/Users/andrew.pennebaker/src/pangrams/node_modules/mocha/lib/runner.js:308:7)
    at next (/Users/andrew.pennebaker/src/pangrams/node_modules/mocha/lib/runner.js:246:23)
    at null (/Users/andrew.pennebaker/src/pangrams/node_modules/mocha/lib/runner.js:275:5)
    at processImmediate (timers.js:363:15)

  5) pangrams isogram should handle true positives:
     ContractError: on `object()`
(contract was wrapped at: /Users/andrew.pennebaker/src/pangrams/node_modules/rho-contracts/index.js:5)
Expected contract, but got undefined
for the key `0` of the hash.
at position .fieldContracts
in contract:
c.fun({ fieldContracts: c.optional(c.hash(c.contract)) } -> c.objectContractObject)

    at null (/Users/andrew.pennebaker/src/pangrams/lib/pangrams.js:128:22)
    at r (/Users/andrew.pennebaker/src/pangrams/node_modules/rho-contracts/contract.impl.js:891:23)
    at null (/Users/andrew.pennebaker/src/pangrams/test/test.js:174:20)
    at callFn (/Users/andrew.pennebaker/src/pangrams/node_modules/mocha/lib/runnable.js:249:21)
    at Runnable.run (/Users/andrew.pennebaker/src/pangrams/node_modules/mocha/lib/runnable.js:242:7)
    at Runner.runTest (/Users/andrew.pennebaker/src/pangrams/node_modules/mocha/lib/runner.js:373:10)
    at null (/Users/andrew.pennebaker/src/pangrams/node_modules/mocha/lib/runner.js:451:12)
    at next (/Users/andrew.pennebaker/src/pangrams/node_modules/mocha/lib/runner.js:298:14)
    at null (/Users/andrew.pennebaker/src/pangrams/node_modules/mocha/lib/runner.js:308:7)
    at next (/Users/andrew.pennebaker/src/pangrams/node_modules/mocha/lib/runner.js:246:23)
    at null (/Users/andrew.pennebaker/src/pangrams/node_modules/mocha/lib/runner.js:275:5)
    at processImmediate (timers.js:363:15)

  6) pangrams heterogram should handle true positives:
     ContractError: on `object()`
(contract was wrapped at: /Users/andrew.pennebaker/src/pangrams/node_modules/rho-contracts/index.js:5)
Expected contract, but got undefined
for the key `0` of the hash.
at position .fieldContracts
in contract:
c.fun({ fieldContracts: c.optional(c.hash(c.contract)) } -> c.objectContractObject)

    at null (/Users/andrew.pennebaker/src/pangrams/lib/pangrams.js:128:22)
    at r (/Users/andrew.pennebaker/src/pangrams/node_modules/rho-contracts/contract.impl.js:891:23)
    at null (/Users/andrew.pennebaker/src/pangrams/lib/pangrams.js:138:18)
    at r (/Users/andrew.pennebaker/src/pangrams/node_modules/rho-contracts/contract.impl.js:891:23)
    at null (/Users/andrew.pennebaker/src/pangrams/test/test.js:197:18)
    at callFn (/Users/andrew.pennebaker/src/pangrams/node_modules/mocha/lib/runnable.js:249:21)
    at Runnable.run (/Users/andrew.pennebaker/src/pangrams/node_modules/mocha/lib/runnable.js:242:7)
    at Runner.runTest (/Users/andrew.pennebaker/src/pangrams/node_modules/mocha/lib/runner.js:373:10)
    at null (/Users/andrew.pennebaker/src/pangrams/node_modules/mocha/lib/runner.js:451:12)
    at next (/Users/andrew.pennebaker/src/pangrams/node_modules/mocha/lib/runner.js:298:14)
    at null (/Users/andrew.pennebaker/src/pangrams/node_modules/mocha/lib/runner.js:308:7)
    at next (/Users/andrew.pennebaker/src/pangrams/node_modules/mocha/lib/runner.js:246:23)
    at null (/Users/andrew.pennebaker/src/pangrams/node_modules/mocha/lib/runner.js:275:5)
    at processImmediate (timers.js:363:15)

  7) pangrams heterogram should handle true negatives:
     ContractError: on `object()`
(contract was wrapped at: /Users/andrew.pennebaker/src/pangrams/node_modules/rho-contracts/index.js:5)
Expected contract, but got undefined
for the key `0` of the hash.
at position .fieldContracts
in contract:
c.fun({ fieldContracts: c.optional(c.hash(c.contract)) } -> c.objectContractObject)

    at null (/Users/andrew.pennebaker/src/pangrams/lib/pangrams.js:128:22)
    at r (/Users/andrew.pennebaker/src/pangrams/node_modules/rho-contracts/contract.impl.js:891:23)
    at null (/Users/andrew.pennebaker/src/pangrams/lib/pangrams.js:138:18)
    at r (/Users/andrew.pennebaker/src/pangrams/node_modules/rho-contracts/contract.impl.js:891:23)
    at null (/Users/andrew.pennebaker/src/pangrams/test/test.js:207:18)
    at callFn (/Users/andrew.pennebaker/src/pangrams/node_modules/mocha/lib/runnable.js:249:21)
    at Runnable.run (/Users/andrew.pennebaker/src/pangrams/node_modules/mocha/lib/runnable.js:242:7)
    at Runner.runTest (/Users/andrew.pennebaker/src/pangrams/node_modules/mocha/lib/runner.js:373:10)
    at null (/Users/andrew.pennebaker/src/pangrams/node_modules/mocha/lib/runner.js:451:12)
    at next (/Users/andrew.pennebaker/src/pangrams/node_modules/mocha/lib/runner.js:298:14)
    at null (/Users/andrew.pennebaker/src/pangrams/node_modules/mocha/lib/runner.js:308:7)
    at next (/Users/andrew.pennebaker/src/pangrams/node_modules/mocha/lib/runner.js:246:23)
    at null (/Users/andrew.pennebaker/src/pangrams/node_modules/mocha/lib/runner.js:275:5)
    at processImmediate (timers.js:363:15)



npm ERR! Test failed.  See above for more details.
npm ERR! not ok code 0
```

Am I using the rho-contracts API correctly?

# Source

https://github.com/mcandre/pangrams

**Comment by gmarceau** [comment]
https://github.com/mcandre/pangrams/pull/13

**Comment by gmarceau** [comment]
@jake-miles can you close this?
